PMS/urls.py
"""PMS URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/stable/topics/http/urls/
"""

from django.urls import path, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('student/', include('student.urls')),
    path('', include('home.urls')),   # root URL points to home app
]

# If you want a static template instead of home.urls, uncomment this line:
# path('', TemplateView.as_view(template_name='pms_index.html')),

company/urls.py
from django.urls import path, re_path
from . import views

app_name = 'company'

urlpatterns = [
    path('signup', views.post_list, name='signup_page'),
    path('login', views.view_home, name='login_page'),
    path('edit', views.view_edit, name='home_page'),
    path('verify', views.verify, name='verify_page'),
    re_path(r'^userc/(?P<username>[A-Za-z_0-9]+)/$', views.profile, name='profile'),
    path('jobreqs', views.Jobreqs, name='job_requirements'),
    path('change_password', views.change_password, name='passchg'),
    path('changed', views.successfull_change, name='passchgsucc'),
    path('listjobs', views.listjobs, name='listjobs'),
    re_path(r'^jobs/(?P<jobid>[0-9]+)/$', views.jobdesc, name='jobdesc'),
    path('applied_msg/', views.jobapplied, name='jobapplied'),
    re_path(r'^student_list/(?P<jobid>[0-9]+)/$', views.view_student_list, name='studlist'),
    path('taken_name/', views.already_taken, name="takenc"),
    re_path(r'^offered/(?P<userid>[A-Za-z_0-9]+)/$', views.offered, name="takenc"),
]

home/urls.py
from django.urls import path
from student import views

app_name = 'home'

urlpatterns = [
    # home/ or /
    path('', views.studentlogin, name='home'),
    path('home/', views.studentlogin, name='home'),
]

student/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'student'

urlpatterns = [
    # home/ or / or student/
    path('student_login/', views.studentlogin, name='student_off'),
    path('auth/', views.auth_view, name='auth'),
    path('edit_details/', views.view_edit, name='edit_page'),
    path('logout/', views.logout, name='logout'),
    
    # Regex patterns for usernames
    re_path(r'users/(?P<username>[A-Za-z_0-9]+)/', views.profile, name='profile'),
    
    # Home and default
    path('home/', views.studentlogin, name='student'),
    path('', views.studentlogin, name='student'),
    
    # Register new student
    path('register/', views.studentregistration, name='student_register'),
    path('listjobs/', views.listjobs, name='list_jobs'),
    path('changed/', views.successfull_change, name='passchgsucc'),
    path('change_password/', views.change_password, name='passchg'),
    path('offer_letter/', views.get_offer, name='offer'),
    path('success/', views.update_details, name="update"),
    path('taken_name/', views.already_taken, name="taken"),
    
    # More regex username patterns
    re_path(r'profile/(?P<username>[A-Za-z_0-9]+)/', views.view_stud_details, name="stud_details"),
    path('download/', views.download, name="download"),
    re_path(r'resume/(?P<username>[A-Za-z_0-9]+)/', views.resumed, name="resumed"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.


def home(request):
    return render(request,'student/student_login.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}PMS{% endblock %}</title>
    {% block meta %}{% endblock %}

    <meta name="description" content="A web portal for hiring process">
    <meta name="author" content="IIT Kharagpur">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Average|Courgette' rel='stylesheet' type='text/css'>

    <!-- Django static files -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    {% block javascript %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Navbar header -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home:home' %}">
                <p class="para" id="title">Placement Management System</p>
            </a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Navbar items -->
        <div class="collapse navbar-collapse mymenu" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block actives %}{% endblock %}">
                    <a href="{% url 'student:student_off' %}">
                        <span class="glyphicon glyphicon-user"></span>&nbsp; Students
                    </a>
                </li>
                <li class="{% block activec %}{% endblock %}">
                    <a href="{% url 'company:login_page' %}">
                        <span class="glyphicon glyphicon-briefcase"></span>&nbsp; Companies
                    </a>
                </li>
                <li>
                    <a href="/admin">
                        <span class="glyphicon glyphicon-lock"></span>&nbsp; Admin
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Main body -->
{% block body %}{% endblock %}

<!-- Bootstrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

</body>
</html>

home/templates/home/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">
                {{ field.errors }}
            </span>
        </div>
        <label class="control-label col-sm-4">
            {{ field.label_tag }}
        </label>
        <div class="col-sm-8">{{ field }}</div>
    </div>

{% endfor %}

home/templates/home/pms_index.html
{% extends 'home/base.html' %}

{% block title %}PMS:Studentshai{% endblock %}

{% block body%}
<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="heading col-sm-offset-2"><strong>Student Login</strong></h2>
                    <br>
                    {% if form.errors %}
                    <p class="error" >Invalid username or password</p>
                    {% endif %}
                    <form class="form-horizontal " action="" method="post" enctype="multipart/form-data">
                        <!--this is for security pupose against click jacking -->
                        {% csrf_token %}
                            {{ form }}
                   <!--     <label class="control-label col-sm-4" for="username"> User name</label>
                        <div class="col-sm-8"> <input type="text" name="username" value="" id="username" ></div>
                        <label class="control-label col-sm-4" for="password"> Password </label>
                         <div class="col-sm-8"><input type="password" name="password" value="" id="password" ></div>
-->

                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                    <div class="col-sm-offset-2">
                        <a href="{% url 'student:student_register' %}">New Registration ...</a>
                    </div>
                </div>
            </div>
                </div>

            <div class="col-md-6">

            </div>
        </div>



    </div>


</div>
{% endblock %}

home/templates/home/recruiter_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="utf-8">
    <title>{% block title %}PMS{% endblock %}</title>
    {% block meta %}
    {% endblock %}

    <meta name="description" content="A web portal for hiring process">
    <meta name="author" content="IIT Kharagpur">
       {% load static %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='http://fonts.googleapis.com/css?family=Average|Courgette' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/sidebar.css' %}">

    <!--Load the path to static files -->

</head>
<body id="backgroundImage">
    <div id="wrapper">
        <div class="overlay"></div>
        <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!--header -->
            <div class="navbar-header">
                <!-- change url here -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"> </span>
                    <span class="icon-bar"> </span>
                    <span class="icon-bar"> </span>
                </button>
            </div>
            <!-- items -->
            <div class="collapse navbar-collapse mymenu" id="topNavBar">

                <ul class="nav navbar-nav navbar-right" >
                         <li class="{% block actives %} {% endblock %}">
                             <a href="/company/userc/{{ username }}">
                                 <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; {% block name %} {%endblock %}
                             </a>
                         </li>
                        <li class="{% block activec %} {% endblock %}">
                             <a href="{%  url 'student:logout' %} ">
                                 <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>&nbsp; Logout
                             </a>
                         </li>

                </ul>
            </div>
        </div>
    </nav>

        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <li class="sidebar-brand">
                    <a href="/company/userc/{{ username }}">
                       PMS:Recruiter
                    </a>
                </li>
                <li>
                    <a href="/company/userc/{{ username }}"><i class="fa fa-fw fa-home"></i> {{ username }}</a>
                </li>
                <li>
                    <a href="/company/edit/"><i class="fa fa-fw fa-folder"></i> Edit Company Info</a>
                </li>
                <li>
                    <a href="/company/jobreqs/"><i class="fa fa-fw fa-file-o"></i> Add Job Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-cog"></i> Edit Your Profile</a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-plus"></i> Job Options <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <!--li class="dropdown-header"></li-->
                    <li><a href="/company/listjobs/">Posted Jobs</a></li>
                    <!--li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li-->
                  </ul>
                </li>
                <li>
                    <a href="company/change_password/"><i class="fa fa-fw fa-bank"></i> Change Password</a>
                </li>
                <!--li>
                    <a href="#"><i class="fa fa-fw fa-dropbox"></i> Page 5</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-twitter"></i> Last page</a>
                </li-->
            </ul>
        </nav>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
          <button type="button" class="hamburger is-closed animated fadeInLeft" data-toggle="offcanvas">
            <span class="hamb-top"></span>
            <span class="hamb-middle"></span>
            <span class="hamb-bottom"></span>
          </button>

            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        {%block main_body %} {%endblock%}
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="{% static 'home/js/sidebar.js' %}"></script>
</body>
</html>

home/templates/home/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="utf-8">
    <title>{% block title %}PMS{% endblock %}</title>
    {% block meta %}
    {% endblock %}

    <meta name="description" content="A web portal for hiring process">
    <meta name="author" content="IIT Kharagpur">
       {% load static %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='http://fonts.googleapis.com/css?family=Average|Courgette' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/sidebar.css' %}">

    <!--Load the path to static files -->

</head>
<body id="backgroundImage">
    <div id="wrapper">
        <div class="overlay"></div>
        <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!--header -->
            <div class="navbar-header">
                <!-- change url here -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"> </span>
                    <span class="icon-bar"> </span>
                    <span class="icon-bar"> </span>
                </button>
            </div>
            <!-- items -->
            <div class="collapse navbar-collapse mymenu" id="topNavBar">

                <ul class="nav navbar-nav navbar-right" >
                         <li class="{% block actives %} {% endblock %}">
                             <a href="#">
                                 <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; {% block name %} {%endblock %}
                             </a>
                         </li>
                        <li class="{% block activec %} {% endblock %}">
                             <a href="{%  url 'student:logout' %} ">
                                 <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>&nbsp; Logout
                             </a>
                         </li>

                </ul>
            </div>
        </div>
    </nav>

        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                       PMS:Student
                    </a>
                </li>
                <li>
                    <a href="/student/users/{{ username }}"><i class="fa fa-fw fa-home"></i> {{ username }}</a>
                </li>
                <li>
                    <a href="/student/listjobs/"><i class="fa fa-fw fa-folder"></i> Job Profiles</a>
                </li>
                <li>
                    <a href="/student/offer_letter/"><i class="fa fa-fw fa-file-o"></i> Offer Letters</a>
                </li>
                <li>
                    <a href="/student/edit_details/"><i class="fa fa-fw fa-cog"></i> Edit Profile</a>
                </li>
                <!--li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-fw fa-plus"></i> Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li class="dropdown-header">Dropdown heading</li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li-->
                <li>
                    <a href="/student/change/"><i class="fa fa-fw fa-bank"></i> Change Password</a>
                </li>
                <!--li>
                    <a href="#"><i class="fa fa-fw fa-dropbox"></i> Page 5</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-twitter"></i> Last page</a>
                </li-->
            </ul>
        </nav>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
          <button type="button" class="hamburger is-closed animated fadeInLeft" data-toggle="offcanvas">
            <span class="hamb-top"></span>
            <span class="hamb-middle"></span>
            <span class="hamb-bottom"></span>
          </button>

            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        {%block main_body %} {%endblock%}
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="{% static 'home/js/sidebar.js' %}"></script>
</body>
</html>