PMS/urls.py
"""PMS URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/stable/topics/http/urls/
"""

from django.urls import path, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('student/', include('student.urls')),
    path('', include('home.urls')),   # root URL points to home app
]

# If you want a static template instead of home.urls, uncomment this line:
# path('', TemplateView.as_view(template_name='pms_index.html')),

student/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'student'

urlpatterns = [
    # home/ or / or student/
    path('student_login/', views.studentlogin, name='student_off'),
    path('auth/', views.auth_view, name='auth'),
    path('edit_details/', views.view_edit, name='edit_page'),
    path('logout/', views.logout, name='logout'),
    
    # Regex patterns for usernames
    re_path(r'users/(?P<username>[A-Za-z_0-9]+)/', views.profile, name='profile'),
    
    # Home and default
    path('home/', views.studentlogin, name='student'),
    path('', views.studentlogin, name='student'),
    
    # Register new student
    path('register/', views.studentregistration, name='student_register'),
    path('listjobs/', views.listjobs, name='list_jobs'),
    path('changed/', views.successfull_change, name='passchgsucc'),
    path('change_password/', views.change_password, name='passchg'),
    path('offer_letter/', views.get_offer, name='offer'),
    path('success/', views.update_details, name="update"),
    path('taken_name/', views.already_taken, name="taken"),
    
    # More regex username patterns
    re_path(r'profile/(?P<username>[A-Za-z_0-9]+)/', views.view_stud_details, name="stud_details"),
    path('download/', views.download, name="download"),
    re_path(r'resume/(?P<username>[A-Za-z_0-9]+)/', views.resumed, name="resumed"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from __future__ import unicode_literals
import os
from django.db import models
from django.urls import reverse
import datetime
from company.models import Job_desc

# File upload helper
def content_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (instance.s_username, ext)
    return os.path.join('documents/', filename)


class StudentDB(models.Model):
    COURSE = (
        ('BTECH', 'bachelors'),
        ('MTECH', 'masters'),
        ('PHD', 'philospher'),
    )
    BRANCH = (
        ('CS', 'computer_science'),
        ('ME', 'mechanical'),
        ('EE', 'electrical'),
    )
    s_username = models.CharField(max_length=250, default='')
    s_name = models.CharField(max_length=250, blank=True)
    s_password = models.CharField(max_length=250, blank=True)
    s_confirm_password = models.CharField(max_length=250, blank=True)
    dob = models.DateField()
    emailid = models.EmailField(blank=True)
    branch = models.CharField(max_length=10, choices=BRANCH, default='CS')
    course = models.CharField(max_length=5, choices=COURSE, default='BTECH')
    s_verified = models.BooleanField(default=False, blank=True)
    s_verification = models.IntegerField(default=0, blank=True)
    contactno = models.CharField(max_length=20, blank=True)
    resume = models.FileField(upload_to=content_file_name, blank=True)

    def __str__(self):
        return str(self.s_username)


class Edit_Details(models.Model):
    s_name = models.CharField(max_length=250, blank=True, null=True)
    emailid = models.EmailField(blank=True)
    qualification = models.CharField(max_length=250, blank=True, null=True)
    resume = models.FileField(upload_to="documents/", blank=True)

    def __str__(self):
        return self.s_name


class Notifications(models.Model):
    jobid = models.ForeignKey(Job_desc, on_delete=models.CASCADE, null=True)
    n_text = models.CharField(max_length=250, null=True)
    old = models.BooleanField(default=True)
    stdid = models.ForeignKey(StudentDB, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.n_text)


class AppliedJob(models.Model):
    jobid = models.ForeignKey(Job_desc, on_delete=models.CASCADE, null=True)
    stdid = models.ForeignKey(StudentDB, on_delete=models.CASCADE, null=True)
    applied = models.BooleanField(default=False)
    got_offer = models.CharField(max_length=250, default="No")

    def __str__(self):
        return str(self.got_offer)


# Example of a future extension:
# class Course(models.Model):
#     course_name = models.CharField(max_length=100)
#     shorthand = models.CharField(max_length=5)

student/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget

from .models import StudentDB, Edit_Details,Notifications
from django.contrib.auth.forms import AuthenticationForm
class Registerform(forms.ModelForm):
    class Meta:
        model=StudentDB
        widgets = {
            's_password': forms.PasswordInput(),
            's_confirm_password' : forms.PasswordInput(),
            'dob': forms.TextInput(attrs={'placeholder': 'MM/DD/YYYY'}),

        }
        fields=['s_username','s_name','s_password','s_confirm_password','dob','emailid','contactno']

class Loginform(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))
    def clean(self):
        pass

class EditForm(forms.ModelForm):
    class Meta :
        model = StudentDB
        fields=['s_name','emailid','resume']
    def clean(self):
        pass

'''class NotifyStudent(forms.ModelForm):
    class Meta:
        model=Notifications
        fields=['n_text','new']
    def clean(self):
        pass'''

student/views.py
import os

from django.core.files import File
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import StudentDB, Edit_Details,Notifications, AppliedJob
from .forms import Registerform, Loginform, EditForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
import random
from django.template import loader
from company.models import Register,Job_desc
# Create your views here.

#class StudentLogin(generic.TemplateView):
 #   template_name = 'student/student_login.html'

#class StudentRegistration(CreateView):
def studentregistration(request):
    status=200
    if request.method=='POST':
        form = Registerform(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            instance = form.save(commit=False)
            # if instance.c_name!=instance.c_confirm_password:
            instance.s_verification = random.randint(1, 1000)
            instance.save()
            # form.save()
            return render(request, 'student/verifymail.html')
        else:
            status = 422
    else:
        form = Registerform()
    return render(request, 'student/studentdb_form.html', {'form': form}, status=status)

    #model= StudentDB
    #fields = ['s_name', 'dob', 'emailid', 'contactno', 'address', 'profile_pic']

def studentlogin(request):
    if request.session.has_key('username') and request.session.has_key('type'):
        user=request.session['username']
        type=request.session['type']
        if(type=="student"):
            return render(request, 'student/loggedin.html', {'username': user})
        else:
            return render(request, 'company/loggedin.html', {'username': user})
    else:
        if request.method == 'POST':
            form = Loginform(data=request.POST)
            print (form.errors)
            print (form.non_field_errors)
            if form.is_valid():
                print("Validation Success")
                user = request.POST['username']
                passw = request.POST['password']
                try:
                    r = StudentDB.objects.filter(s_username__exact=user)
                    if r.filter(s_password__exact=passw):
                        if r.values()[0]['s_verified']:

                            request.session['username'] = user
                            request.session['type']= "student"
                            request.session.set_expiry(300)
                            #form = EditForm()
                            #return HttpResponseRedirect('/student/edit_details',{"username" : user})
                            return render(request,'student/loggedin.html',{'username':user})
                            #return render(request, 'student/student_editform.html', {'form': form})
                        else:
                            return render(request, 'student/verifymail.html')
                    else:
                        return render(request, 'student/invalid_login.html')
                except:
                    return render(request, 'student/invalid_login.html')
                    # instance.save()
            else:
                print("Validation Failed")
                # form = Loginform()
                return render(request, 'student/student_login.html')
        else:
            form = Loginform()
            return render(request, 'student/student_login.html', {'form': form})

#@login_required()

def view_edit(request):
    #print request.session['username']
    if request.session.has_key('username'):
        user = request.session['username']
        if request.method == 'POST':
            form = EditForm(request.POST, request.FILES)
            print (form.errors)
            print (form.non_field_errors)
            if form.is_valid():
                instance = form.save(commit=False)
                # if instance.c_name!=instance.c_confirm_password:
                instance.save()
                # instance.save()
                #print request.session['username']
                return render(request, 'student/student_editform.html', {'form': form,'username': user})
            else:
                print("Validation Failed")
                form = EditForm()
                return render(request, 'student/student_login.html', {'form': form})
        else:
            form = EditForm()
            return render(request, 'student/student_editform.html', {'form': form,'username': user})
    else:
        return HttpResponse('Invalid Access')

def auth_view(request):
    if request.method == 'GET':
        val = int(request.GET['value'])
        name = request.GET['name']
        # print(val,name)
        # print(type(val))
        r = StudentDB.objects.filter(s_username=name)[0]
        print(r)
        if r.s_verification == val:
            print("Success")
            r.s_verified = True
            r.save()
        else:
            pass
        form = EditForm()
        return render(request, 'student/verificationsuccess.html', {'form': form})
'''
def loggedin(request, user):
    if request.session.has_key('username'):
        #user=request.session['username']
        return render(request,'student/'+str(user)+'/', {'username': user})
    else:
        return HttpResponse('Invalid Access')
'''
def profile(request,username):
    if request.session.has_key('username'):
        user=request.session['username']
        s=StudentDB.objects.get(s_username=user)
        print(s.s_username)
        tmpt=Notifications.objects.filter(stdid=s)
        #form = list(tmp.values())  #show any new added job profile only i.e. if (the job id in tmp is not in notification database) and (if in notification database than boolean field is false),then append it to new list and save job_desc in n_text field of notification and set boolean variable in notification to true
        c=tmpt.count()
        ids=[]
        for i in range(0,c):
            ids.append(tmpt.values()[i]['jobid_id'])
        print(ids)
        #ids=list(tmpt.values('jobid_id'))
        form=Job_desc.objects.exclude(pk__in=ids)
        #form.extend(tmp)
        print(form)
        l=list(form.values())
        for i in range(len(l)):
            id=l[i]['id']
            idd=Job_desc.objects.get(pk=id)
            f,t = Notifications.objects.get_or_create(stdid=s,jobid=idd,n_text=str(user))
            if t:
                f.save()
        return render(request,'student/student_profile.html',{'form':form,'username':user})
    else:
        return render(request, 'student/unauthorized.html')

def logout(request):
    if request.session.has_key('username'):
        del request.session['username']
        #auth.logout(request)
        return render(request,'student/logout_student.html')
    else:
        return render(request, 'student/unauthorized.html')

def change_password(request):
    if request.session.has_key('username'):
        user=request.session['username']
        return render(request,'student/change_password.html',{'username':user})
    else:
        return render(request, 'student/unauthorized.html')


def successfull_change(request):
    if request.session.has_key('username'):
        user=request.session['username']
        tmp=StudentDB.objects.get(s_name=user)
        try:
            old=request.POST["piCurrPass"]
            print(old)
            print(tmp.s_password)
            if tmp.s_password==old:
                tmp.s_password=request.POST["piNewPass"]
                tmp.s_confirm_password=request.POST["piNewPass"]
                tmp.save(update_fields=['s_password','s_confirm_password'])
        except:
            return render(request, 'student/unauthorized.html')
        return render(request,'student/loggedin.html',{'username':user})
    else:
        return render(request, 'student/unauthorized.html')
'''
    username= request.POST.get('username','')
    password = request.POST.get('password','')
    user=auth.authenticate(username=username,password=password)

    if user is not None:
        auth.login(request,user)
        return HttpResponseRedirect('/student/loggedin')
    else:
        return HttpResponseRedirect('/student/invalid')


def loggedin(request):
    return render_to_response('student/loggedin.html',{'full_name': request.user.username})

def invalid_login(request):
    return render_to_response('student/invalid_login.html')

def logout(request):
    auth.logout(request)
    return render_to_response('student/logout.html')
'''
def notify(request,username):
    if request.session.has_key('username'):
        user = request.session['username']
        #m=Register.objects.get(c_name=user)
        sbranch = StudentDB.objects.get(s_username=user).branch
        scourse = StudentDB.objects.get(s_username=user).course
        tmp = Job_desc.objects.filter(c_branch=sbranch , c_course=scourse)
        #tmp= Job_desc.objects.all()
        form=list(tmp.values())
        print(form)
        return render(request, 'student/student_profile.html', {'form':form,'username':user})
    else:
        return render(request, 'student/unauthorized.html')

def listjobs(request):
    if request.session.has_key('username'):
        user = request.session['username']
        #m=Register.objects.get(c_name=user)
        sbranch=StudentDB.objects.get(s_username=user).branch
        scourse=StudentDB.objects.get(s_username=user).course
        print(sbranch)
        print(scourse)
        tmp= Job_desc.objects.filter(c_branch=sbranch,c_course=scourse) #need to add check that student is qualified
        form=list(tmp.values())
        print(form)
        return render(request, 'student/list_jobs.html', {'form':form,'username':user})
    else:

student/templates/student/applied_msg.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}
{% block meta %}
<meta http-equiv="refresh" content="1; url=/student/student_login/" />
{%endblock %}
{% block body%}

<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                {% csrf_token %}
                    <h2 class="" id="cursive"><strong>Congratulations</strong></h2>
                    <br>
                    <p>Redirecting to <a href ="/student/student_login">Home Page </a></p>
                </div>
            </div>
            </div>

          </div>
    </div>

</div>
{% endblock %}

student/templates/student/change_password.html
{% extends 'home/user_profile.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block name %}
{{username}}
{% endblock %}

{%block main_body%}

<div class="container-fluid" style="background: rebeccapurple;">
<form class="form-horizontal" action="/student/changed" method="post">
    {% csrf_token %}
<fieldset>

<!-- Form Name -->
<legend class="text-primary">Change Password</legend>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label text-primary" for="piCurrPass">Old Password</label>
  <div class="col-md-4">
    <input id="piCurrPass" name="piCurrPass" type="password" placeholder="" class="form-control input-md" required="">

  </div>
</div>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label text-primary" for="piNewPass">New Password</label>
  <div class="col-md-4">
    <input id="piNewPass" name="piNewPass" type="password" placeholder="" class="form-control input-md" required="">

  </div>
</div>

<!-- Password input-->
<div class="form-group">
  <label class="col-md-4 control-label text-primary" for="piNewPassRepeat">Confirm New Password</label>
  <div class="col-md-4">
    <input id="piNewPassRepeat" name="piNewPassRepeat" type="password" placeholder="" class="form-control input-md" required="">

  </div>
</div>

<!-- Button (Double) -->
<div class="form-group">
  <label class="col-md-4 control-label " for="bCancel"></label>
  <div class="col-md-8">
    <button id="bGodkend" name="bGodkend" class="btn btn-success">Submit</button>
  </div>
</div>

</fieldset>
</form>
</div>
{% endblock %}

student/templates/student/invalid_login.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}
{% block meta %}
<meta http-equiv="refresh" content="1; url=/student/student_login/" />
{%endblock %}
{% block body%}

<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="" id="cursive"><strong>Invalid login</strong></h2>
                    <br>
                    <p>Redirecting to <a href ="/student/student_login">Home Page </a></p>
                </div>
            </div>
            </div>

          </div>
    </div>

</div>
{% endblock %}

student/templates/student/list_jobs.html
{% extends 'home/user_profile.html' %}
{% block name %}
{{username}}
{% endblock %}

{%block main_body%}

<div class="table-responsive listing">
<h1 class="page-header lead">List Of Jobs</h1>
<table class="table table-bordered">
    <tr>
        <th>Job ID</th>
        <th>Job Position</th>
        <th>Company ID</th>
        <th>CTC offered </th>
        <th>Degree Required</th>
        <th>Branch Required</th>
        <th>Application Link</th>

    </tr>
    {% for item in form %}
    <tr>
        <td>{{ item.id}}</td>
        <td>{{ item.c_position }}</td>
        <td>{{ item.register_id }}</td>
        <td>{{ item.c_ctc_offered }}</td>
        <td>{{ item.c_course }}</td>
        <td>{{ item.c_branch }}</td>
        <td> <a href="/company/jobs/{{ item.id }}">Apply</a></td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}

student/templates/student/loggedin.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}

{% block actives %} active {%endblock %}

{%block meta %}<meta http-equiv="refresh" content="2; url=/student/users/{{username}}" /> {% endblock %}
{% block activec %}  {%endblock %}
{% load bootstrap3 %}

{% block body%}

<div id="backgroundImage">

<h2> hi {{ username }} logging in...</h2>
</div>
{%endblock%}

student/templates/student/logout_student.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}

{% block actives %} active {%endblock %}

{%block meta %}<meta http-equiv="refresh" content="2; url=/student/student_login/" /> {% endblock %}
{% block activec %}  {%endblock %}
{% load bootstrap3 %}

{% block body%}

<div id="backgroundImage">

 You have been successfully logged out.....<br>
 Redirecting to <a href="{% url 'student:student_off' %}">Student Login Page</a>

</div>
{%endblock%}




</body>
</html>

student/templates/student/stud_view.html
{% extends 'home/user_profile.html' %}
{% block name %}
{{username}}
{% endblock %}

{%block main_body%}

<div class="listing">
    {% for item in form %}
        <div class="lead page-header">Username</div>
        <div>{{ item.s_username}}</div>
        <div class="lead page-header">Resume</div>
        <div><a href="/student/resume/{{ item.s_username }}">Download</a></div>
        <div class="lead page-header">Student Name</div>
        <div>{{ item.s_name }}</div>
        <div class="lead page-header">Date Of Birth</div>
        <div>{{ item.dob }}</div>

        <div class="lead page-header">Email Id</div>
        <div>{{ item.emailid }}</div>
        <div class="lead page-header">Branch </div>
        <div>{{ item.branch }}</div>
        <div class="lead page-header">Course</div>
        <div>{{ item.course }}</div>
        <div class="lead page-header">Contact Number</div>
        <div>{{ item.contactno }}</div>

            {% endfor %}
</div>
{% endblock %}

student/templates/student/student_editform.html
{% extends 'home/user_profile.html' %}
{% block title %}    Hi {{ username }} {% endblock %}
{% block name %}
{{username}}
{% endblock %}


{%block main_body%}

<div style="background: rebeccapurple;">
    <div class="listing container-fluid">
    <h1>EDIT DETAILS!!!!</h1>
        <div style="color: black;">
    <form  class="form-horizontal" method="POST" action="/student/success/" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_ul }}
         <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-10">
        <button type="submit" class="btn btn-success">Submit</button>
                            </div>

         </div>
</form>
</div>
    </div>
</div>
{% endblock %}

student/templates/student/student_login.html
{% extends 'home/base.html' %}

{% block title %}PMS: Student Login{% endblock %}

{% block actives %}active{% endblock %}
{% block activec %}{% endblock %}

{% block body %}

<div id="backgroundImage">
    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2 class="heading col-sm-offset-2"><strong>Student Login</strong></h2>
                        <br>
                        {% if form.errors %}
                            <p class="error">Invalid username or password</p>
                        {% endif %}

                        <form class="form-horizontal" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form }}

                            <div class="form-group">
                                <div class="col-sm-offset-5 col-sm-10">
                                    <button type="submit" class="btn btn-success">Login</button>
                                </div>
                            </div>
                        </form>

                        <div class="col-sm-offset-0">
                            <a href="{% url 'student:student_register' %}">New Student Registration ...</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <!-- Optional right-side content -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

student/templates/student/student_profile.html
{% extends 'home/user_profile.html' %}
{% block name %}
{{username}}
{% endblock %}

{%block main_body%}
<div class="table-responsive listing">
<h1 class="lead page-header">Notifications for New Jobs</h1>
<table class="table table-bordered">
    <tr>
        <th>Job ID</th>
        <th>Job Position</th>
        <th>Company ID</th>
        <th>CTC offered </th>
        <th>Degree Required</th>
        <th>Branch Required</th>
        <th>Application Link</th>

    </tr>
    {% for item in form %}
    <tr>
        <td>{{ item.id}}</td>
        <td>{{ item.c_position }}</td>
        <td>{{ item.register_id }}</td>
        <td>{{ item.c_ctc_offered }}</td>
        <td>{{ item.c_course }}</td>
        <td>{{ item.c_branch }}</td>
        <td> <a href="/company/jobs/{{ item.id }}">Apply</a></td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}

student/templates/student/studentdb_form.html
{% extends 'home/base.html' %}

{% block title %}Students:Register{% endblock %}
{% block javascript %}

    <script>
        function CheckId() {
            $.get('/student/taken_name/', {username: $('#id_s_username').val()},
                function (data) {
                    if (data == "True") {
                        $('#idval').html("You may use this ID");
                    } else {
                        $('#idval').html("Unavailable");
                    }
                });
        }
        function onChange() {
            //alert("here");
            $("#id_s_username").keyup(function () {
                CheckId()
            });
        }
        $(document).ready(onChange);

    </script>

{% endblock %}
{% block body %}
    <div id="backgroundImage">


        <div class="container-fluid">
            <div class="row modal-body">
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h2 class="heading col-sm-offset-2"><strong>New Student Registration</strong></h2>
                            <br>

                            <form class="form-horizontal " action="" method="post" enctype="multipart/form-data">
                                <!--this is for security pupose against click jacking -->
                                {% csrf_token %}
                                <div class="text-primary container-fluid row" style="vertical-align: middle;">
                                    <div class="col-sm-3">
                                    </div>
                                    <div id="idval" class="col-sm-3 text-danger">
                                    </div>
                                </div>


                                {% for field in form %}
                                    <div class="text-primary container-fluid row" style="vertical-align: middle;">
                                        <div class="col-sm-3">
                                            <label class="text-primary">{{ field.label }}</label>
                                        </div>
                                        <div class="col-sm-3">
                                            {{ field }}
                                        </div>
                                    </div>
                                {% endfor %}

                                <div class="form-group">
                                    <div class="col-sm-offset-5 col-sm-10">
                                        <button type="submit" class="btn btn-success">Register</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>

                <div class="col-md-6">


                </div>
            </div>


        </div>

    </div>
{% endblock %}
<!--id="{% if field.label == 'S username' %} username{% endif %}"-->

student/templates/student/success.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}
{% block meta %}
<meta http-equiv="refresh" content="1; url=/student/student_login/" />
{%endblock %}
{% block body%}

<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="" id="cursive"><strong>Successful</strong></h2>
                    <br>
                    <div>Redirecting to <a href ="/student/student_login">Home Page </a></div>
                </div>
            </div>
            </div>

          </div>
    </div>

</div>
{% endblock %}

student/templates/student/unauthorized.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}
{% block meta %}
<meta http-equiv="refresh" content="1; url=/student/student_login/" />
{%endblock %}
{% block body%}

<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="" id="cursive"><strong>Unauthorized Access... </strong></h2>

                    <p>Redirecting to <a href ="/student/student_login">Home Page </a></p>
                </div>
            </div>
            </div>

          </div>
    </div>

</div>
{% endblock %}

student/templates/student/verifymail.html
{% extends 'home/base.html' %}

{% block title %}Redirecting...{% endblock %}
{% block meta %}
<meta http-equiv="refresh" content="1; url=/student/student_login/" />
{%endblock %}
{% block body%}

<div id="backgroundImage">


    <div class="container-fluid">
        <div class="row modal-body">
            <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2 class="" id="cursive"><strong>Verify through email to complete Registration</strong></h2>
                    <br>
                </div>
            </div>
            </div>

          </div>
    </div>

</div>
{% endblock %}